language: c
jobs:
  include:
    - os: windows
      script:
         - echo $PATH
         - ls /
         - ls /c/ProgramData/chocolatey/
         - ls /c/ProgramData/chocolatey/tools
         - ls /c/ProgramData/chocolatey/bin
#         - ls /c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/usr/bin/x86_64-w64-mingw32
         - ls /mingw64/bin
#         - where mingw32-make
         - mingw32-make
         - ls
#         - /c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/usr/bin/make
#         - bash --login -c make
#        - "travis_wait 50 c:/tools/cygwin/bin/make"
#        - ls /bin
#        - ls /usr/bin
#        - echo $PATH
    - os: linux
      dist: trusty
      addons: 
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages: 
            - bsdtar gperf texinfo help2man gcc-multilib g++-multilib
      script:
        - "travis_wait 50 make"
    - os: osx
      script:
        - "travis_wait 50 make"
#    - os: osx
#      script:
#        - make build-2
before_script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir -p distrib
after_script:
  - ls -la . distrib
on_failure:
  - tail -20 distrib/*error.log
before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
deploy: 
  api_key: $CheckCIDeploy
  file: distrib/*
  file_glob: true
  overwrite: true
  provider: releases
  skip_cleanup: true
  true: 
    branches: 
      only: 
        - master
        - "/v\\d+\\.\\d+[a-z]/"
    repo: Juppit/check-travis
    tags: true
notifications:
  email: false
