language: c
jobs:
  include:
    - os: windows
      script:
#         - echo $PATH
         - mingw32-make
         - ls -a "C:/Users/travis/build/Juppit/Minor-Tests/tarballs"
         - ls -a "C:/Users/travis/build/Juppit/Minor-Tests/src"
#         - tail distrib/*build.log
#         - tail distrib/*error.log
#        - "travis_wait 50 c:/tools/cygwin/bin/make"
    - os: linux
      dist: trusty
      addons: 
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages: 
            - bsdtar gperf texinfo help2man gcc-multilib g++-multilib
      script:
        - "travis_wait 50 make"
    - os: osx
      script:
        - "travis_wait 50 make"
#    - os: osx
#      script:
#        - make build-2
before_script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir -p distrib
after_script:
  - ls -la . distrib
on_failure:
  - tail -20 distrib/*error.log
before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
deploy: 
  api_key: $CheckCIDeploy
  file: distrib/*
  file_glob: true
  overwrite: true
  provider: releases
  skip_cleanup: true
  true: 
    branches: 
      only: 
        - master
        - "/v\\d+\\.\\d+[a-z]/"
    repo: Juppit/check-travis
    tags: true
notifications:
  email: false
