language: bash
jobs:
  include:
    - os: windows
      compiler: gcc
      script:
        - echo $PATH
       # - PATH="/bin:/usr/bin:/c/tools/ruby25/bin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/ProgramData/GooGet:/c/Program Files/Docker:/c/ProgramData/chocolatey/bin:/c/Program Files/CMake/bin:/c/Program Files/Git/cmd:/c/Program Files/LLVM/bin:/c/Program Files/dotnet:/c/Users/travis/AppData/Local/Microsoft/WindowsApps:/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin"
        - PATH="/bin:/usr/bin:/c/tools/ruby25/bin:/c/ProgramData/GooGet:/c/Program Files/Docker:/c/ProgramData/chocolatey/bin:/c/Program Files/CMake/bin:/c/Program Files/Git/cmd:/c/Program Files/LLVM/bin:/c/Program Files/dotnet:/c/Users/travis/AppData/Local/Microsoft/WindowsApps:/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin"
        - echo $PATH
        - wget "https://netcologne.dl.sourceforge.net/project/mingw/MinGW/Extension/bsdtar/basic-bsdtar-2.8.3-1/basic-bsdtar-2.8.3-1-mingw32-bin.zip"
        - unzip basic-bsdtar-2.8.3-1-mingw32-bin.zip
        - mv basic-bsdtar.exe /usr/bin/bsdtar.exe
        - wget "https://netcologne.dl.sourceforge.net/project/gnuwin32/m4/1.4.14-1/m4-1.4.14-1-bin.zip"
        - unzip m4-1.4.14-1-bin.zip
        - mv bin/m4* /usr/bin
        - wget "https://datapacket.dl.sourceforge.net/project/gnuwin32/m4/1.4.14-1/m4-1.4.14-1-dep.zip"
        - unzip m4-1.4.14-1-dep.zip
        - mv bin/regex* /usr/bin
        - CC="C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin\gcc.exe"
        # - "travis_wait 10 make"
        - "travis_wait 50 mingw32-make"
        - cat src/gmp-*/build-Msys64/config.log
    # - os: linux
      # dist: trusty
      # addons: 
        # apt:
          # sources: 
            # - ubuntu-toolchain-r-test
          # packages: 
            # - bsdtar gperf texinfo help2man gcc-multilib g++-multilib
      # script:
         # - ls -a "C:/Users/travis/build/Juppit/Minor-Tests/src"
# #         - "travis_wait 50 make"
    # - os: osx
      # script:
         # - ls -a "C:/Users/travis/build/Juppit/Minor-Tests/src"
# #         - "travis_wait 50 make"
# #    - os: osx
# #      script:
# #        - make build-2
before_script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir -p distrib
after_script:
  - ls -la . distrib
on_failure:
  - tail -20 distrib/*error.log
before_install:
#  - test -n $CC  && unset CC
#  - test -n $CXX && unset CXX
deploy: 
  api_key: $CheckCIDeploy
  file: distrib/*
  file_glob: true
  overwrite: true
  provider: releases
  skip_cleanup: true
  true: 
    branches: 
      only: 
        - master
        - "/v\\d+\\.\\d+[a-z]/"
    repo: Juppit/check-travis
    tags: true
notifications:
  email: false
