language: c
jobs:
  include:
    - os: windows
      script:
        - choco install cygwin
        - choco install cyg-get
        - "ls c:/tools/cygwin/bin/mak*"
        - "ls c:/tools/cygwin/bin/bsdtar*"
        - cyg-get.bat make
        - "ls c:/tools/cygwin/bin/mak*"
        - cyg-get.bat bsdtar
        - "ls c:/tools/cygwin/bin/bsdtar*"
        - cyg-get.bat gperf
        - cyg-get.bat texinfo help2man
        - cyg-get.bat gcc-multilib g++-multilib
        - pwd
        - "c:/tools/cygwin/bin/make.exe --version"
#        - "travis_wait 50 c:/tools/cygwin/bin/make"
#        - ls /bin
#        - ls /usr/bin
#        - echo $PATH
    - os: linux
      dist: trusty
      addons: 
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages: 
            - bsdtar gperf texinfo help2man gcc-multilib g++-multilib
      script:
        - "travis_wait 50 make"
    - os: osx
      script:
        - "travis_wait 50 make"
#    - os: osx
#      script:
#        - make build-2
before_script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir -p distrib
after_script:
  - ls -la . distrib
on_failure:
  - tail -20 distrib/*error.log
before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
deploy: 
  api_key: $CheckCIDeploy
  file: distrib/*
  file_glob: true
  overwrite: true
  provider: releases
  skip_cleanup: true
  true: 
    branches: 
      only: 
        - master
        - "/v\\d+\\.\\d+[a-z]/"
    repo: Juppit/check-travis
    tags: true
notifications:
  email: false
