language: c
jobs:
  include:
    - os: windows
      install:
        - where sh.exe
        - ls -l '/c/program Files/Git/usr/bin' >> git-usr-bin.txt
        - ls -l /usr/bin >> usr-bin.txt
        - ls -l *.txt
        - diff git-usr-bin.txt usr-bin.txt
        - wget "https://netcologne.dl.sourceforge.net/project/mingw/MinGW/Extension/bsdtar/basic-bsdtar-2.8.3-1/basic-bsdtar-2.8.3-1-mingw32-bin.zip" >>/dev/null
        - unzip basic-bsdtar-2.8.3-1-mingw32-bin.zip >>/dev/null
        - mv basic-bsdtar.exe /usr/bin/bsdtar.exe >>/dev/null
        - wget "https://netcologne.dl.sourceforge.net/project/gnuwin32/m4/1.4.14-1/m4-1.4.14-1-bin.zip" >>/dev/null
        - unzip m4-1.4.14-1-bin.zip >>/dev/null
        - mv bin/m4* /usr/bin >>/dev/null
        - wget "https://datapacket.dl.sourceforge.net/project/gnuwin32/m4/1.4.14-1/m4-1.4.14-1-dep.zip" >>/dev/null
        - unzip m4-1.4.14-1-dep.zip >>/dev/null
        - mv bin/regex* /usr/bin >>/dev/null
      script:
        - cd $TRAVIS_BUILD_DIR
        - export PATH='/bin:/usr/bin:/c/ProgramData/chocolatey/bin:/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin'
        - "travis_wait 50 mingw32-make"
before_install:
  - unset CC
  - unset CXX
deploy: 
  api_key: $CheckCIDeploy
  file: distrib/*
  file_glob: true
  overwrite: true
  provider: releases
  skip_cleanup: true
  true: 
    branches: 
      only: 
        - master
        - "/v\\d+\\.\\d+[a-z]/"
    repo: Juppit/check-travis
    tags: true
notifications:
  email: false
